In [1]:
import numpy as np

### Créer un tableau à partir d'une liste

In [67]:
liste = [6, 4, 7, 9, 32]
tableau =np.array(liste)

In [68]:
tableau

array([ 6,  4,  7,  9, 32])

In [9]:
## en 2 dimensions
tab2d = np.array((liste,liste))

In [10]:
tab2d

array([[1, 4, 7, 9, 0],
       [1, 4, 7, 9, 0]])

### Créer un tableau à partir de rien

In [13]:
# tableau de zéros
tab_0 = np.zeros(4,dtype=float)

In [14]:
tab_0

array([0., 0., 0., 0.])

In [15]:
# tableau de 1
tab_1 = np.ones((3,3), dtype=int)

In [16]:
tab_1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
# tableau avec la même valeur : exp(1)
tab_e = np.full((2,4), np.e)

In [20]:
## tableau de 0 à 20 exclus par pas de 2
tab_range = np.arange(0,20,2)

In [21]:
tab_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
## tableau de 0 à 10 avec 20 éléments
tab_space = np.linspace(0, 10, 20)

In [60]:
tab_space

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [41]:
## avec des nombre aléatoires
## tableau 2x7 avec des nombres aléatoires entre 0 et 1
tab_rand = np.random.random((2,7))
## tableau 2x2 avec des valeurs suivant une loi normale
tab_normal = np.random.normal(0, 1, (2,2))
## tableau avec 10 entiers aléatoires de 0 à 20
tab_int = np.random.randint(0,20, 10)

In [42]:
tab_rand

array([[0.0274261 , 0.54654617, 0.89110598, 0.75476147, 0.15101881,
        0.5958476 , 0.48941499],
       [0.38017053, 0.1416914 , 0.28389687, 0.18184266, 0.03831264,
        0.40615664, 0.90228019]])

In [43]:
tab_normal

array([[-0.35140252,  0.35869248],
       [ 0.61076911,  0.89981278]])

In [44]:
tab_int

array([18, 11, 14,  4, 10,  1, 15,  0, 13,  1])

In [48]:
# matrice identité
mat_ind = np.eye(3, dtype=np.float32)

In [49]:
mat_ind

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

### Attributs des tableaux numpy

In [50]:
tab = np.random.randint(0, 10, (3,2))

In [51]:
tab

array([[6, 2],
       [9, 5],
       [0, 4]])

In [56]:
print('dimension :', tab.ndim)
print('taille de chaque dimension :', tab.shape)
print('nombre d\'éléments :', tab.size)

dimension : 2
taille de chaque dimension : (3, 2)
nombre d'éléments : 6


In [58]:
print('nature des éléments du tableau :',tab.dtype)

nature des éléments du tableau : int64


#### Indexing

In [69]:
print('1er élément du tableau :',tableau[0])
print('Dernier élément du tableau :',tableau[-1])

1er élément du tableau : 6
Dernier élément du tableau : 32


In [73]:
tab2d[0,2]

7

In [71]:
print('1er élément du tableau :',tab2d[0][0])

1er élément du tableau : 1


In [76]:
## Modification d'un élément du tableau
tab2d[0,2] = 1515
print(tab2d)

[[   1    4 1515    9    0]
 [   1    4    7    9    0]]


In [79]:
tab_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Slicing

In [78]:
## Sélection des éléments de tab_range du début à la fin par pas de 2
tab_range[0:-1:2]


array([ 0,  4,  8, 12, 16])

In [81]:
## Sélection des éléments de tab_range à partir du 3ème jusqu à la fin
tab_range[2:]

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
## Sélection des éléments de tab_range à partir du dernier par pas de 3 en sens inverse
tab_range[::-3]

array([18, 12,  6,  0])

In [91]:
mat_33 = np.random.random((3,3))

In [92]:
mat_33

array([[0.57955045, 0.09955669, 0.39156947],
       [0.22800431, 0.00750783, 0.27688253],
       [0.30604464, 0.3016332 , 0.99273736]])

In [94]:
# 1ère colonne
mat_33[:,0]

array([0.57955045, 0.22800431, 0.30604464])

In [95]:
# 3ème ligne
mat_33[2,:]

array([0.30604464, 0.3016332 , 0.99273736])

In [103]:
## 2 premières lignes et toutes les colonnes
mat_33[:2,:]

array([[0.57955045, 0.09955669, 0.39156947],
       [0.22800431, 0.00750783, 0.27688253]])

#### Copier un tableau

In [117]:
tab1 = np.random.uniform(0,3,10)

In [118]:
tab1

array([2.80485792, 0.97243768, 0.13996451, 0.58753426, 2.05270576,
       1.86438369, 2.24695193, 1.0704793 , 0.56875677, 1.44702124])

In [109]:
tab2 = tab1
tab2[0] = np.pi

In [112]:
# On teste si la modification a été prise en compte que dans tab 2
tab2 == tab1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [119]:
## Il faut faire une copie afin que seul tab2 soit modifié et non tab1
tab2 = tab1.copy()
tab2[0] = np.pi

In [120]:
tab2 == tab1

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

#### Changer la shape d'un tableau

In [127]:
tab_shape = np.arange(10)

In [129]:
tab_shape

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
tab_shape.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [135]:
tab_shape[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [132]:
tab_shape[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

#### Concaténation de tableaux numpy

In [136]:
tab1 = np.arange(3)
tab2 = np.arange(5,9)

In [141]:
print('tab1 :', tab1)
print('tab2 :', tab2)

tab1 : [0 1 2]
tab2 : [5 6 7 8]


In [139]:
tab_tot = np.concatenate([tab1, tab2])

In [140]:
tab_tot

array([0, 1, 2, 5, 6, 7, 8])

In [170]:
t1 = np.array([0, 1, 2])
t2 = np.random.uniform(1, 2, (2, 3))
t3 = np.array([
    [12],
    [45]
])

In [165]:
np.vstack([t1, t2])

array([[0.        , 1.        , 2.        ],
       [1.67656779, 1.62581099, 1.10771307],
       [1.04541364, 1.39846543, 1.57446806]])

In [172]:
np.hstack([t2, t3])

array([[ 1.73441504,  1.86227875,  1.12136846, 12.        ],
       [ 1.15400101,  1.29670141,  1.22036758, 45.        ]])

In [182]:
np.concatenate([t3,t3],axis=1)

array([[12, 12],
       [45, 45]])

#### Splitting

In [194]:
l1 = np.linspace(0,5,8)

In [217]:
s1, s2, s3 = np.split(l1, [1, 3])

In [218]:
print(s1, s2, s3)

[0.] [0.71428571 1.42857143] [2.14285714 2.85714286 3.57142857 4.28571429 5.        ]


In [223]:
s1, s2 = np.hsplit(l1, [2])

In [226]:
print(s1, s2)

[0.         0.71428571] [1.42857143 2.14285714 2.85714286 3.57142857 4.28571429 5.        ]
